ALENGINE/Models/Inventory.cs
using System;
namespace ALENGINE.Models
{
	public class Inventory
	{
		public int Id { get; set; }
		public string? ItemName { get; set; }
		public string? ManufacturingDate { get; set; }
		public string? ExpiryDate { get; set; }
		public string? Manufacturer { get; set; }
		public int Quantity { get; set; }
		public double  CostPrice { get; set; }
		public double SalesPrice { get; set; }
		public double ExpectedSales { get; set; }
		public double ProfitMargin { get; set; }
		public int SalesQuantity { get; set; }
        public double SalesAmount { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.Now.Date;







	}
}

ALENGINE/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ALENGINE.Data;
using ALENGINE.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ALENGINE.Controllers
{
    public class InventoryController : Controller
    {


        //injection
        private readonly ALENGINEContext _db;

        public InventoryController(ALENGINEContext db)
        {
            _db = db;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index([FromForm] Inventory obj)
        {
            
            _db.Inventories.Add(obj);
            _db.SaveChanges();
            // return RedirectToAction("ServiceRequest", "GeneralUser");
          
            ViewBag.Message = "Item Saved Successfully !";
            ModelState.Clear();
            return View();
        }
    }
}

ALENGINE/Views/Inventory/Index.cshtml
@model ALENGINE.Models.Inventory
<!DOCTYPE html>
<html>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="~/images/favicon.png" type="">

    <title> scriptMEDD </title>

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

    <!-- fonts style -->
    <link href="~/css2/custom.css" rel="stylesheet">

    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="~/css2/custom2.css" />

    <!-- font awesome style -->
    <link href="~/css2/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/css2/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/css2/responsive.css" rel="stylesheet" />

</head>

<body class="sub_page">

    <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section">
            <div class="container">
                <nav class="navbar navbar-expand-lg custom_nav-container ">
                    <a class="navbar-brand" href="index.html">
                        <span>
                            scriptMEDD

                        </span>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class=""> </span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="/">Home </a>
                            </li>
                            <li class="nav-item active">

                                <a class="nav-link" href="/InventoryList" onclick="window.open(this.href, 'windowName', 'width=1000, height=700, left=24, top=24, scrollbars, resizable'); return false;">Inventory List</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="#">User Guide</a>
                            </li>


                        </ul>
                    </div>
                </nav>
            </div>
        </header>
        <!-- end header section -->
    </div>

    <!-- about section -->

    <section class="about_section layout_padding">
        <div class="container  ">
            <div class="row">
                <div class="col-md-12 ">
                    <div class="container">
                        <form  method="post" asp-controller="Inventory" asp-action="Index">
                            <div class="row">
                                <div class="row">
                                    <h4>Inventory | Add Record<hr /></h4>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label">ITID</label>
                                            <div class="col-md-6  mb-10">
                                                <input type="number" class="form-control" readonly>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-md-3 col-form-label">Item Name</label>
                                            <div class="col-md-9 mb-10">
                                                <input type="text" asp-for="ItemName" class="form-control" required>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-3 col-form-label">Manufacturing Date</label>
                                            <div class="col-md-9  mb-10">
                                                <input type="date" asp-for="ManufacturingDate" class="form-control" required />
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-md-3 col-form-label">Expiry Date</label>
                                            <div class="col-md-9  mb-10">
                                                <input type="date" asp-for="ExpiryDate" class="form-control" required />
                                            </div>
                                        </div>

                                    </div>





                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-3 col-form-label">Quantity</label>
                                            <div class="col-md-9  mb-10">
                                                <input type="text" asp-for="Quantity" id="Qty" class="form-control" required>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-md-3 col-form-label">Cost Price</label>
                                            <div class="col-md-9  mb-10">
                                                <input type="text" asp-for="CostPrice" class="form-control" required>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-3 col-form-label">Sales Price</label>
                                            <div class="col-md-9  mb-10">
                                                <input type="text" asp-for="SalesPrice" id="SalesPrice" onchange="add_number()" class="form-control" required>
                                            </div>
                                        </div>
                                            <div class="form-group row">
                                                <label class="col-md-3 col-form-label">Expected Sales</label>
                                            <div class="col-md-9  mb-10">
                                                    <input type="text" asp-for="ExpectedSales" id="Sales" class="form-control" readonly>
                                                </div>
                                            </div>

                                    </div>





                                </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group row">
                                                <label class="col-md-3 col-form-label">Manufacturer</label>
                                            <div class="col-md-9  mb-10">
                                                    <input type="text" asp-for="Manufacturer" class="form-control" required>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group row">
                                                <label class="col-md-3 col-form-label"></label>
                                            <div class="col-md-9  mb-10">
                                                    <input type="hidden" asp-for="ProfitMargin" id="profit" class="form-control">
                                                </div>
                                            </div>


                                        </div>
                                    </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label"></label>
                                            <div class="col-md-6 mb-4">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label"></label>
                                            <div class="col-md-6">
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label"></label>
                                            <div class="col-md-6 mb-4">
                                            </div>

                                        </div>
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label"></label>
                                            <div class="col-md-6 mb-4">
                                                <button type="submit" class="btn btn-success"><i class="fas fa-save fa-sm"> </i>Save Record</button>
                                            </div>
                                        </div>

                                    </div>

                                </div>



                                <script type="text/javascript">
                                    alert("@ViewBag.Message");
                                </script>

                        </form>

                    </div>

                </div>
            </div>
    </section>



    <!-- end about section -->
    <!-- footer section -->
    <footer class="footer_section">
        <div class="container">
        </div>
    </footer>
    <!-- footer section -->
    <!-- jQery -->
    <script>
        function ageCalculator() {
            var userinput = document.getElementById("DOB").value;
            var dob = new Date(userinput);
            if (userinput == null || userinput == '') {
                document.getElementById("message").innerHTML = "**Choose a date please!";
                return false;
            } else {

                //calculate month difference from current date in time
                var month_diff = Date.now() - dob.getTime();

                //convert the calculated difference in date format
                var age_dt = new Date(month_diff);

                //extract year from date
                var year = age_dt.getUTCFullYear();

                //now calculate the age of the user
                var age = Math.abs(year - 1970);

                //display the calculated age
                return document.getElementById("result").value = age;



            }
        }</script>
    <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <!-- bootstrap js -->
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <!-- owl slider -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <!-- custom js -->
    <script type="text/javascript" src="js/custom.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
    </script>

</body>

</html>