ALENGINE/Models/ViewModel/InitiatePaymentViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ALENGINE.Models
{
    public class InitiatePaymentViewModel
    {
        public int Id { get; set; }
        public string? RegistrationNumber { get; set; }
        public string? Surname { get; set; }
        public string? OtherNames { get; set; }
        public string? HomeAddress { get; set; }
        public string? Telephone { get; set; }
        public string? DOB { get; set; }
        public int Age { get; set; }

        public string? Sex { get; set; }
        public string? DateOfFirstVisit { get; set; }

        public string? HealthInsuranceNumber { get; set; }
        public string? CCC { get; set; }
        public int PatientInformationId { get; set; }

        public DateTime DateCreated { get; set; } = DateTime.Now;

        internal static InitiatePaymentViewModel ViewInitData(PatientInformation? initpayment)
        {
            return new InitiatePaymentViewModel
            {


                //show data
                RegistrationNumber = initpayment.RegistrationNumber,
                Surname = initpayment.Surname,
                OtherNames = initpayment.OtherNames,
                HomeAddress = initpayment.HomeAddress,
                Telephone = initpayment.Telephone,
                DOB = initpayment.DOB,
                Age = initpayment.Age,
                Sex = initpayment.Sex,
                DateOfFirstVisit = initpayment.DateCreated.ToString(),
                HealthInsuranceNumber = initpayment.HealthInsuranceNumber,
                CCC = initpayment.Payment,
              PatientInformationId = initpayment.PatientInformationId











    };
        }



    }
}

ALENGINE/Controllers/InitiatePaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ALENGINE.Data;
using ALENGINE.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ALENGINE.Controllers
{
    public class InitiatePaymentController : Controller
    {

        //injection
        private readonly ALENGINEContext _db;

        public InitiatePaymentController(ALENGINEContext db)
        {
            _db = db;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
           



            return View();
        }

        public IActionResult InitPayment(int id)
        {
            // return View(obj);
            var showdatabyID = _db.PatientInformations.FirstOrDefault(m => m.PatientInformationId == id);
            var vm = InitiatePaymentViewModel.ViewInitData(showdatabyID);



            return View(vm);
        }

         [HttpPost]
        public IActionResult InitPayment([FromForm] InitiatePaymentViewModel obj)
        {
            var serviceRequest = new InitialPayment

            {
                RegistrationNumber = obj.RegistrationNumber,
                Surname = obj.Surname,
                OtherNames = obj.OtherNames,
                Telephone = obj.Telephone,
                HomeAddress = obj.HomeAddress,
                HealthInsuranceNumber = obj.HealthInsuranceNumber,
                DOB = obj.DOB,
                Age = obj.Age,
                Sex = obj.Sex,
                DateOfFirstVisit = obj.DateCreated.ToString(),
                CCC = obj.CCC,
                PatientInformationId=obj.PatientInformationId



    };

            _db.InitialPayments.Add(serviceRequest);
            _db.SaveChanges();
            // return RedirectToAction("ServiceRequest", "GeneralUser");
          
            ViewBag.Message = "Request Sent to OPD Successfully";
            ModelState.Clear();
            return View();
        }

    }
}

ALENGINE/Views/InitiatePayment/InitPayment.cshtml
@page
@{
}
@model ALENGINE.Models.InitiatePaymentViewModel;
<!DOCTYPE html>
<html>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="~/images/favicon.png" type="">

    <title> scriptMEDD </title>

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

    <!-- fonts style -->
    <link href="~/css2/custom.css" rel="stylesheet">

    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="~/css2/custom2.css" />

    <!-- font awesome style -->
    <link href="~/css2/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/css2/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/css2/responsive.css" rel="stylesheet" />

</head>

<body class="sub_page">

    <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section">
            <div class="container">
                <nav class="navbar navbar-expand-lg custom_nav-container ">
                    <a class="navbar-brand" href="index.html">
                        <span>
                            scriptMEDD

                        </span>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class=""> </span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="/">Home </a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="/ListPatient"> View Records <span class="sr-only">(current)</span> </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/PatientHistory">Patient History</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="doctors.html">User Guide</a>
                            </li>


                        </ul>
                    </div>
                </nav>
            </div>
        </header>
        <!-- end header section -->
    </div>

    <!-- about section -->

    <section class="about_section layout_padding">
        <div class="container  ">
            <div class="row">
                <div class="col-md-12 ">
                    <div class="container">
                        <form  asp-controller="InitiatePayment" asp-action="InitPayment" enctype="multipart/form-data" role="form" method="post">
                            <div class="row">
                                <div class="row">
                                    <h4>OPD | OPD Request<hr /></h4>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label">Registration Number</label>
                                            <div class="col-md-6 mb-4">
                                                @Html.TextBoxFor(m => m.RegistrationNumber, new { @class = "form-control", @readonly = "readonly" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label">DOB</label>
                                            <div class="col-md-6 mb-4">
                                                @Html.TextBoxFor(m => m.DOB, new { @class = "form-control", @readonly = "readonly" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label">Age</label>
                                            <div class="col-md-6 mb-4">
                                                @Html.TextBoxFor(m => m.Age, new { @class = "form-control", @readonly = "readonly" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label">Sex</label>
                                            <div class="col-md-6 mb-4">
                                                @Html.TextBoxFor(m => m.Sex, new { @class = "form-control", @readonly = "readonly" })
                                            </div>
                                        </div>
                                    </div>





                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label">Surname</label>
                                            <div class="col-md-6 mb-4">
                                                @Html.TextBoxFor(m => m.Surname, new { @class = "form-control", @readonly = "readonly" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label">Othernames</label>
                                            <div class="col-md-6 mb-4">
                                                @Html.TextBoxFor(m => m.OtherNames, new { @class = "form-control", @readonly = "readonly" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label">Telephone</label>
                                            <div class="col-md-6 mb-4">
                                                @Html.TextBoxFor(m => m.Telephone, new { @class = "form-control", @readonly = "readonly" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label">Home Address</label>
                                            <div class="col-md-6 mb-4">
                                                @Html.TextBoxFor(m => m.HomeAddress, new { @class = "form-control", @readonly = "readonly" })
                                            </div>

                                        </div>
                                    </div>





                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label">Health Insurance No.</label>
                                            <div class="col-md-6 mb-4">
                                                @Html.TextBoxFor(m => m.HealthInsuranceNumber, new { @class = "form-control", @readonly = "readonly" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label">PID</label>
                                            <div class="col-md-6 mb-4">
                                                @Html.TextBoxFor(m => m.PatientInformationId, new { @class = "form-control", @readonly = "readonly" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label">CCC.</label>
                                            <div class="col-md-6 mb-4">
                                                @Html.TextBoxFor(m => m.CCC, new { @class = "form-control", @placeholder = "Enter Generated C.C.C", @maxlength = "5" })
                                            </div>
                                        </div>

                                    </div>
                                 

                                </div>


                             
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label"></label>
                                            <div class="col-md-6 mb-4">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label"></label>
                                            <div class="col-md-6">
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label"></label>
                                            <div class="col-md-6 mb-4">
                                            </div>

                                        </div>
                                        <div class="form-group row">
                                            <label class="col-md-6 col-form-label"></label>
                                            <div class="col-md-6 mb-4">
                                                <button type="submit" class="btn btn-success"><i class="fas fa-save fa-sm"> </i>Save Record</button>
                                            </div>
                                        </div>

                                    </div>

                                </div>



                                <script type="text/javascript">
                                    alert("@ViewBag.Message");
                                </script>

                        </form>

                    </div>

                </div>
            </div>
    </section>



    <!-- end about section -->
    <!-- footer section -->
    <footer class="footer_section">
        <div class="container">
          
        </div>
    </footer>
    <!-- footer section -->
    <!-- jQery -->
    <script>
        function ageCalculator() {
            var userinput = document.getElementById("DOB").value;
            var dob = new Date(userinput);
            if (userinput == null || userinput == '') {
                document.getElementById("message").innerHTML = "**Choose a date please!";
                return false;
            } else {

                //calculate month difference from current date in time
                var month_diff = Date.now() - dob.getTime();

                //convert the calculated difference in date format
                var age_dt = new Date(month_diff);

                //extract year from date
                var year = age_dt.getUTCFullYear();

                //now calculate the age of the user
                var age = Math.abs(year - 1970);

                //display the calculated age
                return document.getElementById("result").value = age;



            }
        }</script>
    <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <!-- bootstrap js -->
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <!-- owl slider -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <!-- custom js -->
    <script type="text/javascript" src="js/custom.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
    </script>

</body>

</html>